version: "0.1"
networks:
  nginx-net:

services:
  api-service:
    container_name: api-service
    build: ./api-service/
    ports:
      - "8080:8080"
    networks:
      - nginx-net

  blog-service:
    container_name: blog-service
    build: ./blog-service/
    ports:
      - "9000:9000"
    networks:
      - nginx-net

  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "8000:8000"
    networks:
      - nginx-net

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - nginx-net

