spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54323/demo?useSSL=false
    username: postgres
    password: postgres
redis:
  host: localhost
  port: 6379
